version: '3'

services:
  flask_app:
    image: image_flask_app
    container_name: container_flask_app
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flaskdb:5432/postgres
    depends_on:
      - flaskdb

  flaskdb:
    image: postgres:latest
    container_name: container_flask_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - './:/src'

volumes:
  flaskdb:
    driver: local
